CREATE TABLE IF NOT EXISTS waiting_room_policies (
  id TEXT PRIMARY KEY,
  domain_id TEXT NOT NULL UNIQUE REFERENCES domains(id) ON DELETE CASCADE,
  enabled BOOLEAN NOT NULL DEFAULT false,
  mode TEXT NOT NULL DEFAULT 'monitoring',
  state TEXT NOT NULL DEFAULT 'disabled',
  reason TEXT NULL,
  rps_threshold INTEGER NOT NULL DEFAULT 100,
  active_origin_threshold INTEGER NOT NULL DEFAULT 20,
  origin_latency_ms_threshold INTEGER NOT NULL DEFAULT 3000,
  origin_error_rate_threshold INTEGER NOT NULL DEFAULT 50,
  admission_rate_per_minute INTEGER NOT NULL DEFAULT 60,
  queue_limit INTEGER NOT NULL DEFAULT 1000,
  per_client_ticket_limit INTEGER NOT NULL DEFAULT 3,
  ticket_ttl_seconds INTEGER NOT NULL DEFAULT 300,
  admission_ttl_seconds INTEGER NOT NULL DEFAULT 900,
  status_poll_seconds INTEGER NOT NULL DEFAULT 5,
  jitter_seconds INTEGER NOT NULL DEFAULT 4,
  unhealthy_windows INTEGER NOT NULL DEFAULT 3,
  healthy_windows INTEGER NOT NULL DEFAULT 3,
  minimum_state_seconds INTEGER NOT NULL DEFAULT 60,
  recovery_ramp_percent INTEGER NOT NULL DEFAULT 25,
  manual_override_until BIGINT NULL,
  trusted_cidrs_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  waiting_room_title TEXT NOT NULL DEFAULT 'Traffic is high',
  waiting_room_message TEXT NOT NULL DEFAULT 'You are in a short waiting room while this site protects its origin.',
  counters_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  CHECK (mode IN ('monitoring','automatic','manual')),
  CHECK (state IN ('disabled','monitoring','healthy','entering_overload','overloaded','recovering','manual_emergency')),
  CHECK (rps_threshold BETWEEN 1 AND 1000000),
  CHECK (active_origin_threshold BETWEEN 1 AND 1000000),
  CHECK (origin_latency_ms_threshold BETWEEN 1 AND 600000),
  CHECK (origin_error_rate_threshold BETWEEN 1 AND 100),
  CHECK (admission_rate_per_minute BETWEEN 1 AND 1000000),
  CHECK (queue_limit BETWEEN 1 AND 1000000),
  CHECK (per_client_ticket_limit BETWEEN 1 AND 1000),
  CHECK (ticket_ttl_seconds BETWEEN 30 AND 3600),
  CHECK (admission_ttl_seconds BETWEEN 60 AND 86400),
  CHECK (status_poll_seconds BETWEEN 2 AND 300),
  CHECK (jitter_seconds BETWEEN 0 AND 300),
  CHECK (unhealthy_windows BETWEEN 1 AND 100),
  CHECK (healthy_windows BETWEEN 1 AND 100),
  CHECK (minimum_state_seconds BETWEEN 1 AND 86400),
  CHECK (recovery_ramp_percent BETWEEN 1 AND 100)
);
