ALTER TABLE waf_rules ADD COLUMN IF NOT EXISTS waf_group_id TEXT NULL;
ALTER TABLE waf_rules ADD COLUMN IF NOT EXISTS waf_severity TEXT NULL;
ALTER TABLE waf_rules ADD COLUMN IF NOT EXISTS waf_confidence TEXT NULL;
ALTER TABLE waf_rules ADD COLUMN IF NOT EXISTS waf_safe_reason TEXT NULL;
