ALTER TABLE config_state ADD COLUMN IF NOT EXISTS dirty BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE config_state ADD COLUMN IF NOT EXISTS dirty_at BIGINT NULL;
ALTER TABLE config_state ADD COLUMN IF NOT EXISTS published_at BIGINT NULL;
ALTER TABLE config_state ADD COLUMN IF NOT EXISTS last_publish_error TEXT NULL;
ALTER TABLE config_state ADD COLUMN IF NOT EXISTS publishing_started_at BIGINT NULL;
