ALTER TABLE redirect_rules ADD COLUMN IF NOT EXISTS priority INTEGER NOT NULL DEFAULT 100;
ALTER TABLE redirect_rules ADD COLUMN IF NOT EXISTS match_type TEXT NOT NULL DEFAULT 'exact_path';
ALTER TABLE redirect_rules ADD COLUMN IF NOT EXISTS preserve_query BOOLEAN NOT NULL DEFAULT true;
