ALTER TABLE waf_rules ADD COLUMN IF NOT EXISTS name TEXT NULL;
ALTER TABLE waf_rules ADD COLUMN IF NOT EXISTS priority INTEGER NOT NULL DEFAULT 100;
ALTER TABLE waf_rules ADD COLUMN IF NOT EXISTS action TEXT NOT NULL DEFAULT 'block';
ALTER TABLE waf_rules ADD COLUMN IF NOT EXISTS description TEXT NULL;
