ALTER TABLE usage_rollups ADD COLUMN IF NOT EXISTS cache_status TEXT NULL;
ALTER TABLE usage_rollups ADD COLUMN IF NOT EXISTS rule_id TEXT NULL;
ALTER TABLE usage_rollups ADD COLUMN IF NOT EXISTS request_id TEXT NULL;
ALTER TABLE usage_rollups ADD COLUMN IF NOT EXISTS origin_status INTEGER NULL;
ALTER TABLE usage_rollups ADD COLUMN IF NOT EXISTS origin_time_ms INTEGER NULL;
