<template>
  <section class="space-y-4">
    <div class="card grid gap-4 p-5 md:grid-cols-4"><label>Routing mode<select v-model="routing.routing_mode" class="input"><option value="geo">Geo</option><option value="anycast">Anycast</option><option value="dns_only">DNS only</option></select></label><label>Anycast IPv4<input v-model="routing.anycast_ipv4" class="input" /></label><label>Anycast IPv6<input v-model="routing.anycast_ipv6" class="input" /></label><button class="button-primary self-end" @click="saveRouting">Save routing</button></div>
    <div class="flex justify-end"><button class="button-primary" @click="startCreate">Add DNS record</button></div>
    <form v-if="editing" class="card grid gap-4 p-5 md:grid-cols-3" @submit.prevent="save"><label>Type<select v-model="form.type" class="input"><option>A</option><option>AAAA</option><option>CNAME</option><option>TXT</option><option>MX</option></select></label><label>Name<input v-model="form.name" class="input" /></label><label>Content<input v-model="form.content" class="input" /></label><label>TTL<input v-model="form.ttl" type="number" class="input" /></label><label class="flex items-center gap-2"><input v-model="form.proxied" type="checkbox" /> Proxied</label><div class="flex gap-2"><button class="button-primary">Save</button><button type="button" class="button-secondary" @click="editing=false">Cancel</button></div></form>
    <EmptyState v-if="records.length===0" title="No DNS records" message="Add the first DNS record for this domain." />
    <DataTable v-else title="DNS Records" :rows="records" :columns="columns"><template #proxied="{ row }"><button class="button-secondary px-2 py-1 text-xs" @click="toggle(row)">{{ row.proxied ? 'Proxied' : 'DNS only' }}</button></template><template #actions="{ row }"><div class="flex gap-2"><button class="button-secondary px-2 py-1 text-xs" @click="preview(row)">Preview</button><button class="button-secondary px-2 py-1 text-xs" @click="edit(row)">Edit</button><ConfirmDangerButton class="px-2 py-1 text-xs" confirm-text="Delete this DNS record?" @confirm="remove(row)">Delete</ConfirmDangerButton></div></template></DataTable>
    <pre v-if="previewResult" class="card overflow-auto p-4 text-xs">{{ JSON.stringify(previewResult,null,2) }}</pre>
  </section>
</template>
<script setup lang="ts">import { onMounted, reactive, ref, watch } from 'vue'; import DataTable from '@/components/ui/DataTable.vue'; import EmptyState from '@/components/ui/EmptyState.vue'; import ConfirmDangerButton from '@/components/forms/ConfirmDangerButton.vue'; import { dnsApi } from '@/lib/api/dns'; import type { DnsRecord, DomainRoutingSettings } from '@/types'; const props=defineProps<{domainId:string}>(); const records=ref<DnsRecord[]>([]); const editing=ref(false); const editingId=ref(''); const previewResult=ref<unknown>(); const form=reactive({type:'A',name:'@',content:'',ttl:300,proxied:true}); const routing=reactive<Partial<DomainRoutingSettings>>({routing_mode:'geo',geo_health_port:443,geo_selector:'pickclosest',anycast_ipv4:'',anycast_ipv6:'',anycast_cname:''}); const columns=[{key:'name',label:'Name'},{key:'type',label:'Type'},{key:'content',label:'Origin'},{key:'public_content',label:'Public'},{key:'ttl',label:'TTL'},{key:'proxied',label:'Proxy'},{key:'actions',label:'Actions'}]; async function load(){records.value=await dnsApi.list(props.domainId);Object.assign(routing,await dnsApi.routing(props.domainId));} function startCreate(){editingId.value='';Object.assign(form,{type:'A',name:'@',content:'',ttl:300,proxied:true});editing.value=true;} function edit(row:Record<string,unknown>){editingId.value=String(row.id);Object.assign(form,{type:String(row.type),name:String(row.name),content:String(row.content),ttl:Number(row.ttl),proxied:Boolean(row.proxied)});editing.value=true;} async function save(){if(editingId.value)await dnsApi.update(props.domainId,editingId.value,form);else await dnsApi.create(props.domainId,form);editing.value=false;await load();} async function remove(row:Record<string,unknown>){await dnsApi.remove(props.domainId,String(row.id));await load();} async function toggle(row:Record<string,unknown>){await dnsApi.update(props.domainId,String(row.id),{proxied:!row.proxied});await load();} async function preview(row:Record<string,unknown>){previewResult.value=await dnsApi.previewRouting(props.domainId,String(row.id));} async function saveRouting(){await dnsApi.updateRouting(props.domainId,routing);await load();} watch(()=>props.domainId,load);onMounted(load);</script>
