<template>
  <section class="space-y-4">
    <form class="card grid gap-4 p-5 md:grid-cols-3" @submit.prevent="saveSettings"><label class="flex items-center gap-2"><input v-model="settings.enabled" type="checkbox" /> Cache enabled</label><label>Default edge TTL<input v-model="settings.default_edge_ttl_seconds" type="number" class="input" /></label><label class="flex items-center gap-2"><input v-model="settings.respect_origin_cache_control" type="checkbox" /> Respect origin Cache-Control</label><button class="button-primary">Save cache settings</button></form>
    <div class="card space-y-3 p-5"><h2 class="text-lg font-bold">Purge cache</h2><div class="flex flex-wrap gap-2"><button class="button-secondary" @click="purge('everything')">Purge all</button><input v-model="purgeValue" class="input max-w-sm" placeholder="/assets/ or https://..." /><button class="button-secondary" @click="purge('prefix')">Purge prefix</button><button class="button-secondary" @click="purge('url')">Purge URL</button></div></div>
    <DomainRulesTab :domain-id="domainId" title="Cache Rules" summary="Override cache TTL for matching path prefixes." :fields="fields" :columns="columns" :list="() => cacheApi.rules(domainId)" :create="(v) => cacheApi.createRule(domainId,v)" :update="(id,v) => cacheApi.updateRule(domainId,id,v)" :remove="(id) => cacheApi.removeRule(domainId,id)" />
    <DataTable title="Recent Purges" :rows="purges" :columns="purgeColumns" />
  </section>
</template>
<script setup lang="ts">import { onMounted, reactive, ref, watch } from 'vue'; import DomainRulesTab from './DomainRulesTab.vue'; import DataTable from '@/components/ui/DataTable.vue'; import { cacheApi } from '@/lib/api/cache'; import { purgeApi } from '@/lib/api/purge'; const props=defineProps<{domainId:string}>(); const settings=reactive({enabled:true,default_edge_ttl_seconds:3600,default_browser_ttl_seconds:null as number|null,cache_query_string_mode:'include_all',respect_origin_cache_control:true,cache_authorized_requests:false,stale_if_error_seconds:86400}); const purges=ref<Record<string,unknown>[]>([]); const purgeValue=ref(''); const fields=[{key:'enabled',label:'Enabled',type:'checkbox' as const,default:true},{key:'path_prefix',label:'Path prefix',default:'/'},{key:'ttl_seconds',label:'TTL seconds',type:'number' as const,default:3600}]; const columns=[{key:'enabled',label:'Enabled'},{key:'path_prefix',label:'Path'},{key:'ttl_seconds',label:'TTL'},{key:'actions',label:'Actions'}]; const purgeColumns=[{key:'type',label:'Type'},{key:'value',label:'Value'},{key:'status',label:'Status'},{key:'created_at',label:'Created'}]; async function load(){Object.assign(settings,await cacheApi.settings(props.domainId));purges.value=await purgeApi.list(props.domainId) as unknown as Record<string,unknown>[];} async function saveSettings(){await cacheApi.updateSettings(props.domainId,settings);} async function purge(type:string){if(!window.confirm(`Purge ${type} cache for this domain?`))return;await purgeApi.create(props.domainId,{type,value:purgeValue.value||undefined});await load();} watch(()=>props.domainId,load);onMounted(load);</script>
