<template>
  <section class="space-y-4">
    <form class="card flex flex-wrap items-end gap-4 p-5" @submit.prevent="saveSettings"><label class="flex items-center gap-2"><input v-model="settings.force_https" type="checkbox" /> Force HTTPS</label><label>Minimum TLS<select v-model="settings.min_tls_version" class="input"><option value="1.2">TLS 1.2</option><option value="1.3">TLS 1.3</option></select></label><button class="button-primary">Save SSL settings</button></form>
    <div class="flex flex-wrap justify-end gap-2"><button class="button-primary" @click="issue">Issue ACME certificate</button><button class="button-secondary" @click="check">Run certificate check</button></div>
    <EmptyState v-if="certificates.length===0" title="No certificates" message="Issue an ACME certificate or import one through the API." />
    <DataTable v-else title="Certificates" :rows="rows" :columns="columns"><template #expiry="{ row }"><span :class="Number(row.days_until_expiry ?? row.days_left) < 30 ? 'font-bold text-amber-600' : ''">{{ row.days_until_expiry ?? row.days_left ?? 'Unknown' }} days</span></template></DataTable>
  </section>
</template>
<script setup lang="ts">import { computed,onMounted,reactive,ref,watch } from 'vue'; import DataTable from '@/components/ui/DataTable.vue'; import EmptyState from '@/components/ui/EmptyState.vue'; import { sslApi } from '@/lib/api/ssl'; import type { SslCertificate } from '@/types'; const props=defineProps<{domainId:string}>(); const certificates=ref<SslCertificate[]>([]); const settings=reactive({force_https:true,min_tls_version:'1.2' as '1.2'|'1.3'}); const columns=[{key:'hostname',label:'Hostname'},{key:'status',label:'Status'},{key:'issuer',label:'Issuer'},{key:'expiry',label:'Expiry'},{key:'last_error',label:'Error'}]; const rows=computed(()=>certificates.value.map(c=>({...c,expiry:''}))); async function load(){const [certs,current]=await Promise.all([sslApi.certificates(props.domainId),sslApi.settings(props.domainId)]);certificates.value=certs;Object.assign(settings,current);} async function saveSettings(){await sslApi.updateSettings(props.domainId,settings);} async function issue(){await sslApi.issueAcme(props.domainId);await load();} async function check(){await sslApi.check(props.domainId);await load();} watch(()=>props.domainId,load);onMounted(load);</script>
