<template><section class="flex min-h-[calc(100vh-8rem)] flex-col space-y-6">
  <div class="flex flex-wrap items-start justify-between gap-3"><div><h1 class="text-3xl font-black">Overview</h1><p class="text-slate-500">A 24-hour operational summary across the CDN.</p></div><ReportExportButton title="Overview" :data="reportData"/></div>
  <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><div v-for="card in cards" :key="card.label" class="card p-4"><p class="text-sm text-slate-500">{{card.label}}</p><p class="mt-2 text-2xl font-black">{{card.value}}</p></div></div>
  <div class="card p-5"><h2 class="text-lg font-black">Needs attention</h2><p v-if="!warnings.length" class="mt-3 text-sm text-emerald-700">No active warnings.</p><ul v-else class="mt-3 space-y-3"><li v-for="warning in warnings" :key="warning.message" class="flex items-center justify-between gap-3 rounded-xl border border-amber-200 p-3"><div><StatusBadge :status="warning.severity"/><span class="ml-2 text-sm">{{warning.message}}</span></div><RouterLink :to="warning.link" class="font-bold text-cyan-700">Fix</RouterLink></li></ul></div>
</section></template>
<script setup lang="ts">
import{computed,onMounted,ref}from'vue';import{RouterLink}from'vue-router';import StatusBadge from'@/components/ui/StatusBadge.vue';import ReportExportButton from'@/components/reports/ReportExportButton.vue';import{overviewApi}from'@/lib/api/overview';import{formatBytes,formatPercent}from'@/lib/utils/format';import type{Overview,OverviewWarning}from'@/types';
const overview=ref<Overview|null>(null),warnings=ref<OverviewWarning[]>([]);
const cards=computed(()=>[{label:'Domains',value:overview.value?.domains_count??0},{label:'Active domains',value:overview.value?.active_domains??0},{label:'Requests (24h)',value:overview.value?.total_requests_24h??0},{label:'Bandwidth (24h)',value:formatBytes(overview.value?.bandwidth_24h_bytes??0)},{label:'Cache hit ratio',value:formatPercent(overview.value?.cache_hit_ratio_24h??0)},{label:'Edges online',value:overview.value?.edge_online??0},{label:'Edges offline',value:overview.value?.edge_offline??0},{label:'Security events',value:overview.value?.security_events_24h??0},{label:'SSL expiring',value:overview.value?.ssl_expiring_count??0}]);
const reportData=computed(()=>({metrics:overview.value,warnings:warnings.value}));
onMounted(async()=>{[overview.value,warnings.value]=await Promise.all([overviewApi.get(),overviewApi.warnings()]);});
</script>
