<template><section class="space-y-6"><div><h1 class="text-3xl font-black text-white">Troubleshooting</h1><p class="text-slate-400">Guided checks for core, edge, DNS, cache, security, and SSL.</p></div><div class="grid gap-4 xl:grid-cols-2"><div v-for="card in cards" :key="card.title" class="card p-5"><div class="flex items-center justify-between"><h2 class="text-xl font-bold text-white">{{ card.title }}</h2><StatusBadge :status="card.status" /></div><p class="mt-3 text-sm text-slate-300"><b>Why this matters:</b> {{ card.why }}</p><p class="mt-2 text-sm text-slate-300"><b>How to fix:</b> {{ card.fix }}</p><button class="button-secondary mt-4" @click="card.run">Run check</button><pre class="mt-4 overflow-auto rounded-xl bg-slate-950 p-3 text-xs text-slate-400">{{ JSON.stringify(card.result, null, 2) }}</pre></div></div></section></template>
<script setup lang="ts">
import { reactive } from 'vue'; import StatusBadge from '@/components/ui/StatusBadge.vue'; import { healthApi } from '@/lib/api/health'; import { edgesApi } from '@/lib/api/edges'; import { sitesApi } from '@/lib/api/sites';
const cards = reactive([
  { title: 'Core API', status: 'unknown', why: 'The SPA depends on the control plane for all management actions.', fix: 'Check core /health and /ready, then verify VITE_CDNLITE_CORE_URL and reverse proxy auth.', result: null as unknown, async run() { this.result = await Promise.allSettled([healthApi.coreHealth(), healthApi.coreReady()]); this.status = 'info'; } },
  { title: 'Edge', status: 'unknown', why: 'Edges must be reachable and heartbeating to serve traffic with fresh config.', fix: 'Check edge /ready, edge-agent token registration, and stale heartbeat nodes.', result: null as unknown, async run() { this.result = await Promise.allSettled([healthApi.edgeReady(), edgesApi.list()]); this.status = 'info'; } },
  { title: 'DNS', status: 'unknown', why: 'Incorrect proxied DNS sends users around the CDN or to the wrong origin.', fix: 'Review proxied records, public content, edge target, and PowerDNS API errors.', result: null as unknown, async run() { this.result = await sitesApi.list(); this.status = 'info'; } },
  { title: 'Cache', status: 'unknown', why: 'Low hit ratio increases origin load and latency.', fix: 'Review disabled cache settings, recent purges, query-string mode, and stale-if-error.', result: 'Select a site in Cache to inspect settings.', async run() { this.status = 'info'; } },
  { title: 'Security', status: 'unknown', why: 'WAF and rate limit decisions explain blocked or suspicious traffic.', fix: 'Review recent events, top blocked sites, and overly broad WAF rules.', result: 'Open Security / WAF and Event Viewer.', async run() { this.status = 'info'; } },
  { title: 'SSL', status: 'unknown', why: 'Expired or mismatched certificates break HTTPS.', fix: 'Run SSL check, review days-left, and re-import matching PEM certificate/key.', result: 'Open SSL for site-scoped certificate inventory.', async run() { this.status = 'info'; } },
]);
</script>
