# PowerDNS secondary/replica - managed by CDNLite
launch=gsqlite3
gsqlite3-database=/var/lib/powerdns/pdns.sqlite3

primary=no
secondary=yes
autosecondary=yes
superslave=yes

local-address=0.0.0.0
local-port=53
log-dns-queries=no
loglevel=4
