events {}

http {
  server {
    listen 80;
    location / {
      default_type application/json;
      return 200 '{"ok":true,"origin_scheme":"http","origin_host":"$host"}';
    }
  }

  server {
    listen 443 ssl;
    ssl_certificate /tmp/origin.crt;
    ssl_certificate_key /tmp/origin.key;
    location / {
      default_type application/json;
      return 200 '{"ok":true,"origin_scheme":"https","origin_host":"$host"}';
    }
  }
}
